# Generated by Django 5.0.6 on 2025-10-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="download_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="translationjob",
            name="download_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
