# Generated by Django 5.0.6 on 2025-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_translationjob_download_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationjob",
            name="download_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
    ]
