# Generated by Django 5.2.7 on 2025-11-06 22:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_translationjob_download_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedactionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=256)),
                ("source_blob_url", models.URLField(max_length=2048)),
                (
                    "target_blob_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("status", models.CharField(default="notStarted", max_length=32)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "download_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("download_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redaction_jobs",
                        to="api.profile",
                    ),
                ),
            ],
        ),
    ]
