# Generated by Django 5.2.7 on 2025-11-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_redactionjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactionjob",
            name="operation_location",
            field=models.URLField(default="", max_length=2048),
            preserve_default=False,
        ),
    ]
