# Generated by Django 6.0 on 2026-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_redactionjob_operation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='redactionjob',
            name='entity_download_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='redactionjob',
            name='entity_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
