-- Plain INSERT statements for table `api_languagecode` (code, name)
-- No ON CONFLICT/UPSERT logic included.

INSERT INTO api_languagecode (code, name) VALUES ('af', 'Afrikaans');
INSERT INTO api_languagecode (code, name) VALUES ('sq', 'Albanian');
INSERT INTO api_languagecode (code, name) VALUES ('ar', 'Arabic');
INSERT INTO api_languagecode (code, name) VALUES ('az', 'Azerbaijani (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('ba', 'Bashkir');
INSERT INTO api_languagecode (code, name) VALUES ('eu', 'Basque');
INSERT INTO api_languagecode (code, name) VALUES ('bs', 'Bosnian (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('bg', 'Bulgarian');
INSERT INTO api_languagecode (code, name) VALUES ('yue', 'Cantonese (Traditional)');
INSERT INTO api_languagecode (code, name) VALUES ('ca', 'Catalan');
INSERT INTO api_languagecode (code, name) VALUES ('lzh', 'Chinese (Literary)');
INSERT INTO api_languagecode (code, name) VALUES ('zh-Hans', 'Chinese Simplified');
INSERT INTO api_languagecode (code, name) VALUES ('zh-Hant', 'Chinese Traditional');
INSERT INTO api_languagecode (code, name) VALUES ('hr', 'Croatian');
INSERT INTO api_languagecode (code, name) VALUES ('cs', 'Czech');
INSERT INTO api_languagecode (code, name) VALUES ('da', 'Danish');
INSERT INTO api_languagecode (code, name) VALUES ('nl', 'Dutch');
INSERT INTO api_languagecode (code, name) VALUES ('en', 'English');
INSERT INTO api_languagecode (code, name) VALUES ('et', 'Estonian');
INSERT INTO api_languagecode (code, name) VALUES ('fo', 'Faroese');
INSERT INTO api_languagecode (code, name) VALUES ('fj', 'Fijian');
INSERT INTO api_languagecode (code, name) VALUES ('fil', 'Filipino');
INSERT INTO api_languagecode (code, name) VALUES ('fi', 'Finnish');
INSERT INTO api_languagecode (code, name) VALUES ('fr', 'French');
INSERT INTO api_languagecode (code, name) VALUES ('fr-ca', 'French (Canada)');
INSERT INTO api_languagecode (code, name) VALUES ('gl', 'Galician');
INSERT INTO api_languagecode (code, name) VALUES ('de', 'German');
INSERT INTO api_languagecode (code, name) VALUES ('ht', 'Haitian Creole');
INSERT INTO api_languagecode (code, name) VALUES ('hi', 'Hindi');
INSERT INTO api_languagecode (code, name) VALUES ('mww', 'Hmong Daw (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('hu', 'Hungarian');
INSERT INTO api_languagecode (code, name) VALUES ('is', 'Icelandic');
INSERT INTO api_languagecode (code, name) VALUES ('id', 'Indonesian');
INSERT INTO api_languagecode (code, name) VALUES ('ia', 'Interlingua');
INSERT INTO api_languagecode (code, name) VALUES ('ikt', 'Inuinnaqtun');
INSERT INTO api_languagecode (code, name) VALUES ('iu-Latn', 'Inuktitut (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('ga', 'Irish');
INSERT INTO api_languagecode (code, name) VALUES ('it', 'Italian');
INSERT INTO api_languagecode (code, name) VALUES ('ja', 'Japanese');
INSERT INTO api_languagecode (code, name) VALUES ('kn', 'Kannada');
INSERT INTO api_languagecode (code, name) VALUES ('kk-cyrl', 'Kazakh (Cyrillic)');
INSERT INTO api_languagecode (code, name) VALUES ('kk-latn', 'Kazakh (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('ko', 'Korean');
INSERT INTO api_languagecode (code, name) VALUES ('ku-latn', 'Kurdish (Latin) (Northern)');
INSERT INTO api_languagecode (code, name) VALUES ('ky', 'Kyrgyz (Cyrillic)');
INSERT INTO api_languagecode (code, name) VALUES ('lv', 'Latvian');
INSERT INTO api_languagecode (code, name) VALUES ('lt', 'Lithuanian');
INSERT INTO api_languagecode (code, name) VALUES ('mk', 'Macedonian');
INSERT INTO api_languagecode (code, name) VALUES ('mg', 'Malagasy');
INSERT INTO api_languagecode (code, name) VALUES ('ms', 'Malay (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('ml', 'Malayalam');
INSERT INTO api_languagecode (code, name) VALUES ('mt', 'Maltese');
INSERT INTO api_languagecode (code, name) VALUES ('mi', 'Maori');
INSERT INTO api_languagecode (code, name) VALUES ('mr', 'Marathi');
INSERT INTO api_languagecode (code, name) VALUES ('mn-Cyrl', 'Mongolian (Cyrillic)');
INSERT INTO api_languagecode (code, name) VALUES ('ne', 'Nepali');
INSERT INTO api_languagecode (code, name) VALUES ('nb', 'Norwegian Bokmål');
INSERT INTO api_languagecode (code, name) VALUES ('pl', 'Polish');
INSERT INTO api_languagecode (code, name) VALUES ('pt-br', 'Portuguese (Brazil)');
INSERT INTO api_languagecode (code, name) VALUES ('pt-pt', 'Portuguese (Portugal)');
INSERT INTO api_languagecode (code, name) VALUES ('pa', 'Punjabi');
INSERT INTO api_languagecode (code, name) VALUES ('otq', 'Queretaro Otomi');
INSERT INTO api_languagecode (code, name) VALUES ('ro', 'Romanian');
INSERT INTO api_languagecode (code, name) VALUES ('ru', 'Russian');
INSERT INTO api_languagecode (code, name) VALUES ('sm', 'Samoan (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('sr-Cyrl', 'Serbian (Cyrillic)');
INSERT INTO api_languagecode (code, name) VALUES ('sr-latn', 'Serbian (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('sk', 'Slovak');
INSERT INTO api_languagecode (code, name) VALUES ('sl', 'Slovenian');
INSERT INTO api_languagecode (code, name) VALUES ('so', 'Somali');
INSERT INTO api_languagecode (code, name) VALUES ('es', 'Spanish');
INSERT INTO api_languagecode (code, name) VALUES ('sw', 'Swahili (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('sv', 'Swedish');
INSERT INTO api_languagecode (code, name) VALUES ('ty', 'Tahitian');
INSERT INTO api_languagecode (code, name) VALUES ('ta', 'Tamil');
INSERT INTO api_languagecode (code, name) VALUES ('tt', 'Tatar (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('te', 'Telugu');
INSERT INTO api_languagecode (code, name) VALUES ('to', 'Tongan');
INSERT INTO api_languagecode (code, name) VALUES ('tr', 'Turkish');
INSERT INTO api_languagecode (code, name) VALUES ('tk', 'Turkmen (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('uk', 'Ukrainian');
INSERT INTO api_languagecode (code, name) VALUES ('hsb', 'Upper Sorbian');
INSERT INTO api_languagecode (code, name) VALUES ('uz', 'Uzbek (Latin)');
INSERT INTO api_languagecode (code, name) VALUES ('vi', 'Vietnamese');
INSERT INTO api_languagecode (code, name) VALUES ('cy', 'Welsh');
INSERT INTO api_languagecode (code, name) VALUES ('yua', 'Yucatec Maya');
INSERT INTO api_languagecode (code, name) VALUES ('zu', 'Zulu');